### ISSUE TITLE
你好！请问在vue3中如何使用呢

### ISSUE THREAD

**Issue by wukongyang** [mumuy/widget-qrcode#1]

**Comment by mumuy** [comment]
引入脚本和标签即可

**Comment by wukongyang** [comment]
> 引入脚本和标签即可

试过，不太行，只展示了普通二维码，无法切换类型

**Comment by mumuy** [comment]
有演示地址 https://passer-by.com/widget-qrcode/

**Comment by Z-Hansu** [comment]
> 有演示地址 https://passer-by.com/widget-qrcode/

我尝试过，在 html 文件中使用是没问题的。但是在 vue 文件中，会出现以下提示：
`[Vue warn]: Failed setting prop "template" on <widget-qrcode>: value is invalid. TypeError: Cannot set property template of #<t> which has only a getter`
请问该如何解决？

**Comment by mumuy** [comment]
现在试试看，vue不允许一个组件只有getter没有setter

**Comment by Z-Hansu** [comment]
> 现在试试看，vue不允许一个组件只有getter没有setter

可以了:)
