### ISSUE TITLE
vue3使用提示找不到模块

### ISSUE THREAD

**Issue by zhengb1019** [mumuy/widget-qrcode#4]
`npm i widget-qrcode`
通过npm安装之后，在vue文件中引入组件报错：Failed to resolve entry for package "widget-qrcode". The package may have incorrect main/module/exports specified in its package.json.
![Uploading 57.png…]()

**Comment by mumuy** [comment]
应该好了，之前没做UMD处理

**Comment by oirep** [comment]
好像又出现这问题了？
