### ISSUE TITLE
有些机型导致二维码被拉伸, 覆盖机型不多

### ISSUE THREAD

**Issue by Super-Doro** [mumuy/widget-qrcode#8]
![Uploading ff249864ee52e48a391cfeaaf4085af.png…]()

**Comment by Super-Doro** [comment]
VIVO，Y31S
Redmi K30s Ultra

**Comment by Super-Doro** [comment]
![ff249864ee52e48a391cfeaaf4085af](https://github.com/user-attachments/assets/6c17afa4-8e90-4a5a-82cd-7b5d91f48635)

**Comment by mumuy** [comment]
默认宽高300，如果你要等比例，可以 width:200px;height:auto;这样设置
